apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-bullmq
  name: nestjs-bullmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-bullmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-bullmq
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - image: edwardoboh/nestjs-bullmq
        env:
          - name: REDIS_HOST
            value: 'helm-chart-redis-master'
          - name: REDIS_PORT
            value: '6379'
        name: nestjs-bullmq
        ports:
        - containerPort: 3000
        resources: {}
status: {}
